---
title: "TI_Analysis"
author: "Petra Borovska"
date: "25 Äervna 2020"
output: 
        html_document:
        toc: true
        toc_float: true
        toc_depth: 2
        number_sections: true
        theme: flatly
        

---
## Cleaning

clean environment and console

```{r clean_console}
cat("\014")
```



```{r clean_envir}
rm(list = ls())
```



Installing all necessary packages for data preparation 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# ## install packages
# install.packages("knitr")
# install.packages("devtools")
# install.packages("here")
# install.packages("tidyverse")
# devtools::install_github("hadley/emo")
# install.packages("viridis")
# devtools::install_github("mikabr/ggpirate")
# install.packages("afex")
# install.packages("bootES")
# 


# install.packages("ez")

## load packages
library(knitr)
library(devtools)
library(here)
library(tidyverse)
library(emo)
library(viridis)
library(ggpirate)
library(afex)
library(emmeans)
library(multcomp)
library(bootES)
library(broom)
library(ez)

```







```{r mySim}

## Our model parameters
# id = subjNr
# dv = prop
# within = pairType
# between = cond
# type = 3


# 0 = wake
# 1 = sleep

# 0 = prem
# 1 = inference


set.seed(1234)                  ## initial seed, not important for interpretation
intercept = 0.5                 ## knowing that dv is between 0 and 1
beta.condition = 0.5              ## knowing that dv is between 0 and 1
nr.simulations = 200
residual.variation = 1          ## used as sd for simulating random numbers with mean 0
alpha = 0.05
sample.sim.size = 240
sample.mod.size = 80            ## actual sample size entering the model
sample.size.Y = 2000

# Store p-values here:                  ## rep is just making a space in the variable
p.vals=rep(x=0, time= nr.simulations)   ## creating empty variable for p values with size of number of simulations
c.d=rep(x=0, time= nr.simulations)      ## creating empty variable for standardized dependent variable set with size of number of simulations



c = c(1,1,0,0)

subj = rep(1:60, each=4)
subj = as.integer(subj)

cond = rep(0:1, each=2, len=240)
cond = as.factor(cond)

pairType = rep(0:1, 120)
pairType = as.factor(pairType)

## columns for simulated df
subj = rep(1:60, each=4)
cond = rep(0:1, each=2, len=240)
pairType = rep(0:1, 120)


for(a in 1:nr.simulations){
        
	# Sample condition and gender.
	# condition.sample = sample(c(0,1), size= sample.sim.size, replace=T)
	# condition.sample_pair = sample(c(0,1), size= sample.sim.size, replace=T)
        
        condition.sample = cond
        condition.sample_pair = pairType

	
	# Simulate data. 
        
        Y = rnorm(n= sample.size.Y, sd=residual.variation, mean=0)
        
	Y = round(Y,2)                                      ## rounding number to non decimal
	
	Y = as.data.frame(Y)
	Y = Y[Y$Y >= 0 & Y$Y <=1, ]
	Y = Y[1:240]
	Y = as.numeric(Y)
        
        
	Y = intercept + beta.condition* condition.sample * condition.sample_pair + Y
	
# 
	condition.sample = as.factor(condition.sample)
	condition.sample_pair = as.factor(condition.sample_pair)
	subj = as.integer(subj)


	sim.data = data.frame(cbind(subj, condition.sample, condition.sample_pair, Y))
	                        ## creating df with two columns - condition
	                                                    ## and y as dv
	names(sim.data) <- c("subj", "cond", "pairType", "Y")


	# (2) Running the model
	# Select sample
	sim.data.sub = sim.data[1:sample.mod.size, ]  ## selecting smaller                                                                                       data set given above as                                                                                    sample.mod.size



#
	full.model_tidy = aov_ez(
        data = sim.data.sub,
        id = "subj",
        dv = "Y",
        within = c("pairType", "cond"),
        type = 3
        )
        
	# full.model.sum = summary(full.model_tidy)                   ## getting summary
	
	p.vals[a] <- full.model_tidy$anova_table[3,6]         ## locating p value from the summary table
	
}



# Look at the result.
sum(p.vals<0.05)/nr.simulations       ## get a proportion of significant values


sum_p = sum(p.vals<0.05)

```

```{r model_aov}

subj = rep(1:60, each=4)
subj = as.integer(subj)

cond = rep(0:1, each=2, len=240)
cond = as.factor(cond)

pairType = rep(0:1, 120)
pairType = as.factor(pairType)

Y = rnorm(n= 240, sd=residual.variation, mean=0)

myData = data.frame(cbind(subj, cond, pairType, Y))


full.model = ezANOVA(
        data = myData,
        dv = Y,
        within = c(pairType, cond),
        wid = subj,
        type = 3

)  




full.model_tidy_2 = aov_ez(
        data = myData,
        id = "subj",
        dv = "Y",
        within = c("pairType", "cond"),
        type = 3
)

sum_tidy = summary(full.model_tidy)
class(sum_tidy)

sum_tidy_df = tibble(sum_tidy)

full.model_tidy_2
full.model_tidy_2$anova_table[3,6]


lm_at= lm(Y~cond)
heh = summary(lm_at)
heh$coefficients


```

```{r trying_functions_sim}

x <- matrix(1:10, ncol=2)


x_scale <- scale(x, center = TRUE, scale = TRUE)



sleepG <- sample(
        x=0:1, 
        replace=TRUE,
        rnorm(20, mean=0.75)
        )


sample(0:1)



rtruncnorm <- function(N, mean = 0, sd = 1, a = -Inf, b = Inf) {
  if (a > b) stop('Error: Truncation range is empty');
  U <- runif(N, pnorm(a, mean, sd), pnorm(b, mean, sd));
  qnorm(U, mean, sd); }

rtruncnorm(20, mean = 0.75, sd = 1.86)


rnorm(20, mean = 0.75, sd = 1.86)

runif(20)

sam = c(0.75, 0.68, 0.88)


sample(sam, 2)

sam = runif(20, min=0.55, max=1)
samAvg = sum(sam)/20

samSD = sd(sam)



```


