---
title           : "Preregistration: Transitive inference in children"
shorttitle      : "Transitive Infrence"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Petra Borovská
    affiliation : 1
  - name        : Jacob Bellmund
    affiliation : "2"
  - name        : Artem Karew
    affiliation : "2"    


affiliation:
  - id          : 1
    institution : University of Leipzig
  - id          : 2
    institution : Max Planck Institute for Human Cognitive and Brain Sciences



output: prereg::cos_prereg
---

# Study Information

## Title
<!-- Provide the working title of your study. It may be the same title that you submit for publication of your final manuscript, but it is not a requirement. The title should be a specific and informative description of a project. Vague titles such as 'Fruit fly preregistration plan' are not appropriate.

Example: Effect of sugar on brownie tastiness. -->
Influence of Sleep on Transitive Inference in Children

`r rmarkdown::metadata$title`


## Description
<!-- Please give a brief description of your study, including some background, the purpose of the of the study, or broad research questions. The description should be no longer than the length of an abstract. It can give some context for the proposed study, but great detail is not needed here for your preregistration.

Example: Though there is strong evidence to suggest that sugar affects taste preferences, the effect has never been demonstrated in brownies. Therefore, we will measure taste preference for four different levels of sugar concentration in a standard brownie recipe to determine if the effect exists in this pastry. -->

The main aim of this study is to assess an influence of sleep or longer resting period on transtive inference ability in children in age 8-9 year old. The transitive inference task is an ability to generalized from existing knowledge forming a novel combinations and thus providing an insight to basic cognitive skills, children possess (Zeithamova, 2012; Ellenbogen, 2007). Since couple of decades an open discussion about when exactly are children capable of passing the transitive inference task prevails (Bryant & Trabasso, 1971) and this question remains also valid for adults, whose performance on this task is not above chance immediately after training compared to participants that where tested after a delay (Ellenbogen, 2007). This effect is related to internal brain processes involving a memory integration mechanism triggered by hippocampal-medial prefrontal circuit. As a result of hippocampal replay during sleep or longer delay, it is hypothesized that by recombination of previously learned knowledge a novel connection, i.e. inference, occur. We expect to see similar effect in children of age 8 and 9, assuming that by this age, they are already making inference similarly to adults. However, it is also possible that they will not pass the task, thus revealing that the processes are not yet fully developed. Similarly it is still open which kind of strategy children or even adults using when making the inference. It is speculated that the judgement on more distant pairs are done faster, when the whole hierarchy is encoded as single representation, opposite to retrieval based mechanism, since more distant pairs recquire more time to retrieve more complex information in comparison to less distant pairs (Zeithamova, 2012). It remains unclear if children generally use different strategy or the strategy is affected by influence of the sleep or delay. The goal is to behaviorally assess the two strategy approach by using response time measure.        



## Hypotheses
<!-- List specific, concise, and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here. If a specific interaction or moderation is important to your research, you can list that as a separate hypothesis.

Example: If taste affects preference, then mean preference indices will be higher with higher concentrations of sugar. -->

1. Performance on inference pairs will be significantly higher in delay condition vs. non-delay.

2. Performance on 2 degree pairs increase after delay vs. non-delay condition.

3. Response time decreases after delay vs. non-delay condition.

4. Response time is higher in more distant pairs vs. less distant pairs.

5. Premise pairs correlate with inference pairs.


# Design Plan
<!-- In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. -->


## Study type

**Experiment**. A researcher randomly assigns treatments to study subjects, this includes field or lab experiments. This is also known as an intervention experiment and includes randomized controlled trials.


## Blinding
<!-- Blinding describes who is aware of the experimental manipulations within a study. Select all that apply. Is there any additional blinding in this study? -->

<!--No blinding is involved in this study. -->

For studies that involve human subjects, they will not know the treatment group to which they have been assigned.



## Study design
<!-- Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies.

This question has a variety of possible answers. The key is for a researcher to be as detailed as is necessary given the specifics of their design. Be careful to determine if every parameter has been specified in the description of the study design. There may be some overlap between this question and the following questions. That is OK, as long as sufficient detail is given in one of the areas to provide all of the requested information. For example, if the study design describes a complete factorial, 2 X 3 design and the treatments and levels are specified previously, you do not have to repeat that information.

Example: We have a between subjects design with 1 factor (sugar by mass) with 4 levels. -->

We have a mixed design with 2 x 2 factors of one being between (delay by non-delay) and one within-subject (premise pair by inference pair) with peformance score as dependent measure. Additionally we use similar design for contrasting one degree inference pairs and two degree inference pairs with assumption that premise pair performance will be similar in both groups. Further we use the same model for second dependent measure, response times. Lastly, we look at linear regression model of inference pairs as function of middle premise pair performance and possibly conduct an exploratory analysis on detailed type of pairs in case the model will be significant.

The study is divided into training and testing, both organized into blocks. Training contain 5 mandatory blocks with 10 trials each, followed by futher blocks where score is counted on middle pairs (B > C, C > D, D > E) to assess appropriatelly if the hiearachy was properly learned, as the first and last pairs are easily learned, because A is always correct and F is always incorrect. If the participant pass the block above 75% correct in two consecutive blocks, the training is over. And testing is followed depending on the group assignment. In the delay condition, test is submitted after 24 hours. In the non-delay condition the test follows after 10 minutes break from training. The test includes 5 blocks, each consisting of 18 trials.   

Each stimulus is a representation of an item in the hierarchy and each participant receive his own order of the hierarchy, which is individual and unique, meaning that 2 participants cannot have the same hierarchy. So for example *A* is represented by *monster1* and *B* is represented by *monster2*. Correct response is then defined by the default hierarchy order, when A is always higher than B, B than C, etc. The hierarchy is 6-item long, from A to F.  

The study is conducted on computer in online manner. The stimuli are presented in random order, such that none of the items of each pair shown on the screen are followed by the same item of the next stimuli pair (e.g. when A > B presented, nor A nor B will follow on the next trial). The side of the stimuli pair is counterbalanced, such that each stimuli pair is presented twice in each block, the higher item of the pair always on the left or on the right side to prevent any side preferences.


## Randomization
<!-- If you are doing a randomized study, how will you randomize, and at what level? Typical randomization techniques include: simple, block, stratified, and adaptive covariate randomization. If randomization is required for the study, the method should be specified here, not simply the source of random numbers.

Example: We will use block randomization, where each participant will be randomly assigned to one of the four equally sized, predetermined blocks. The random number list used to create these four blocks will be created using the web applications available at http://random.org. -->

We will use simple randomization, each participant will be randomly assigned to the same-sized group - delay or non-delay, prior recruiting. Randomization will be done in R, using *sample()* function. For the details please see R markdown document attached.  


# Sampling Plan
<!-- In this section we’ll ask you to describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Please keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study. -->


For the data collection, database of Max Planck Institute for Human Cognitive and Brain Sciences will be used for recruitment of participants. We plan to collect sample of size 40, assuming that the recruitment sample will be in reality higher due to dropouts, etc.



## Existing data
<!-- Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data. Therefore, creating a research plan in which existing data will be used presents unique challenges. Please select the description that best describes your situation. Please do not hesitate to contact us if you have questions about how to answer this question (prereg@cos.io). -->

**Registration prior to creation of data**. As of the date of submission of this research plan for preregistration, the data have not yet been collected, created, or realized. 

*Note:* the data used for analysis has not been collected, however adult pilot has been done and used for analysis preparation. 



## Explanation of existing data
<!-- If you indicate that you will be using some data that already exist in this study, please describe the steps you have taken to assure that you are unaware of any patterns or summary statistics in the data. This may include an explanation of how access to the data has been limited, who has observed the data, or how you have avoided observing any analysis of the specific data you will use in your study.

An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point.

Example: An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point. -->

Apart from pilot data, that won't be included in analysis, no further existing data will be used.


## Data collection procedures
<!-- Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that donÍt include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.

The answer to this question requires a specific set of instructions so that another person could repeat the data collection procedures and recreate the study population. Alternatively, if the study population would be unable to be reproduced because it relies on a specific set of circumstances unlikely to be recreated (e.g., a community of people from a specific time and location), the criteria and methods for creating the group and the rationale for this unique set of subjects should be clear.

Example: Participants will be recruited through advertisements at local pastry shops. Participants will be paid $10 for agreeing to participate (raised to $30 if our sample size is not reached within 15 days of beginning recruitment). Participants must be at least 18 years old and be able to eat the ingredients of the pastries. -->

Participants will be recruited from the Max Planck database as mentioned above and paid a voucher in amount of 10 Euro. Target group are children of age 8 and 9 without any serious medical history. The consent will be collected prior of testing in form of online confirmation from parents and children. Participants who does not finish the whole procedure will be excluded. Similarly participants that exceed 30 training blocks will be excluded.   


## Sample size
<!-- Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis? For some studies, this will simply be the number of samples or the number of clusters. For others, this could be an expected range, minimum, or maximum number.

Example: Our target sample size is 280 participants. We will attempt to recruit up to 320, assuming that not all will complete the total task. -->

Our target is 40 children, 20 in each group, however we will recruite at least 50 assuming that not all complete the task.


## Sample size rationale
<!-- This could include a power analysis or an arbitrary constraint such as time, money, or personnel. This gives you an opportunity to specifically state how the sample size will be determined. A wide range of possible answers is acceptable; remember that transparency is more important than principled justifications. If you state any reason for a sample size upfront, it is better than stating no reason and leaving the reader to "fill in the blanks." Acceptable rationales include: a power analysis, an arbitrary number of subjects, or a number based on time or monetary constraints.

Example: We used the software program G*Power to conduct a power analysis. Our goal was to obtain .95 power to detect a medium effect size of .25 at the standard .05 alpha error probability. -->

In order to estimate recquired sample size, power analysis using G*Power program was used. Calculation was based on main previous research paper from Ellenbogen (2007). Because not all descriptive data were provided in the paper, calculation was based on F statistics information, following a study by Lakens (2013), when calculating the effect size.    

Parameters:    
**F tests: ANOVA: Repeated measures, within-between interaction**    
A priori: Compute required sample size  

Effect size: 0.37  
Alpha err prob: 0.05   
Power: 0.80   
Number of groups: 2   
Number of measurements: 2   
Corr among rep measures: 0   
Nonsphericity correction: 1   

Resulting total sample size was calculated on 32.   

Additionally R power analysis was used to verify the result. The recquired sample size based on R power analysis slightly exceeds 40 participants given the power of 0.80.    
Please see attached R script.  



## Stopping rule
<!-- If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. 

You may specify a stopping rule based on p-values only in the specific case of sequential analyses with pre-specified checkpoints, alphas levels, and stopping rules. Unacceptable rationales include stopping based on p-values if checkpoints and stopping rules are not specified. If you have control over your sample size, then including a stopping rule is not necessary, though it must be clear in this question or a previous question how an exact sample size is attained.

Example: We will post participant sign-up slots by week on the preceding Friday night, with 20 spots posted per week. We will post 20 new slots each week if, on that Friday night, we are below 320 participants. -->

The data collection will be stopped when 40 participants complete the procedure.



# Variables
<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->

*Dependent measures*. 

**Performance:** percent correct, if selected picture will be higher in defined hierarchy, e.g. A ? B, the correct response is A.  
**Response times:** calculated from stimulus presentation until key response given.  

*Independent measures*:   

**Group**: delay and non-delay  
Delay = testing is conducted after 24 hours from training.  
Non-delay = testing is conducted after 10 minutes break from testing.  

**Pair Type**: premise and inference    
Premise = all pairs not involving inference judgments: A>B, B>C, C>D, D>E, E>F, the total score is 50 in all blocks of testing.   
Inference = all pairs involving inference judgments and not involving first and last pair: B>D, C>E, B>E, the total score is 30    

One Degree Pair = all pairs with the distance of one member apart: B>D, C>E, the total score is 20 in all blocks of testing.   
Two Degree Pair = all pairs with the distance of two member apart: B>E, the total score is 10 in all blocks of testing.





## Manipulated variables
<!-- Describe all variables you plan to manipulate and the levels or treatment arms of each variable. This is not applicable to any observational study. For any experimental manipulation, you should give a precise definition of each manipulated variable. This must include a precise description of the levels at which each variable will be set, or a specific definition for each categorical treatment. For example, “loud or quiet,” should instead give either a precise decibel level or a means of recreating each level. 'Presence/absence' or 'positive/negative' is an acceptable description if the variable is precisely described.

Example: We manipulated the percentage of sugar by mass added to brownies. The four levels of this categorical variable are: 15%, 20%, 25%, or 40% cane sugar by mass. -->

We manipulated in which group participants are assign to, delay vs. non-delay and which pair type was presented: premise, inference, one degree, two degree.


## Measured variables
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.'

Example: The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being 'not at all', 7 being 'a great deal') and 'How good did the brownie taste' (on a scale of 1-7, 1 being 'very bad', 7 being 'very good'). -->

We will use two types of dependent measures, percent correct, calculated from correct responses 1 or 0 summed across all trials and blocks and expressed in proportions and response times calculated from stimulus presentation until a key response (see above).


## Indices
<!-- If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.

If you are using multiple pieces of data to construct a single variable, how will this occur? Both the data that are included and the formula or weights for each measure must be specified. Standard summary statistics, such as "means" do not require a formula, though more complicated indices require either the exact formula or, if it is an established index in the field, the index must be unambiguously defined. For example, "biodiversity index" is too broad, whereas "Shannon’s biodiversity index" is appropriate.

Example: We will take the mean of the two questions above to create a single measure of 'brownie enjoyment.'  -->

We will calculate sum of correct responses in each pair category that will be expressed in proportion and averaged when collapsing a category, e.g. one degree and two degree are firstly calculated separately as proportions and then averaged when including as one category - iference pairs.


# Analysis Plan
<!-- You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.

A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. -->

We plan to conduct mixed ANOVA and linear regression. Firstly, the data sets will be prepared to for appropirate models, e.g. long format of the data for ANOVA. We will conduct an assumption checks for both types of test. We will provide descriptive statistics including mean, median, sd, standar errors and confidence intervals. Similarly effect sizes will be calculated.



## Statistical models
<!-- What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions, subgroup analyses, pairwise or complex contrasts, or follow-up tests from omnibus tests. If you plan on using any positive controls, negative controls, or manipulation checks you may mention that here. Remember that any test not included here must be noted as an exploratory test in your final article.

This is perhaps the most important and most complicated question within the preregistration. As with all of the other questions, the key is to provide a specific recipe for analyzing the collected data. Ask yourself: is enough detail provided to run the same analysis again with the information provided by the user? Be aware for instances where the statistical models appear specific, but actually leave openings for the precise test. See the following examples:

- If someone specifies a 2x3 ANOVA with both factors within subjects, there is still flexibility with the various types of ANOVAs that could be run. Either a repeated measures ANOVA (RMANOVA) or a multivariate ANOVA (MANOVA) could be used for that design, which are two different tests. 
- If you are going to perform a sequential analysis and check after 50, 100, and 150 samples, you must also specify the p-values you’ll test against at those three points.

Example:  We will use a one-way between subjects ANOVA to analyze our results. The manipulated, categorical independent variable is 'sugar' whereas the dependent variable is our taste index. -->


We plan to conduct mixed ANOVA, involving at least 3 models.    

1. With performance as outcome variable and with one between factor *group* with two levels - delay and non-delay and one within-subject factor *pair type* with two levels - premise and inference.    

2. With performance as outcome variable and with one between factor *group* with two levels - delay and non-delay and one within-subject factor *pair type* with two levels - one degree and second degree inference.     

3. Model with response time as outcome variable and with one between factor *group* with two levels - delay and non-delay and one within-subject factor *pair type* with two levels - one degree and second degree inference.   


## Transformations
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. If any categorical predictors are included in a regression, indicate how those variables will be coded (e.g. dummy coding, summation coding, etc.) and what the reference category will be.

Example: The "Effect of sugar on brownie tastiness" does not require any additional transformations. However, if it were using a regression analysis and each level of sweet had been categorically described (e.g. not sweet, somewhat sweet, sweet, and very sweet), 'sweet' could be dummy coded with 'not sweet' as the reference category. -->

No data transformation will be conducted with performance measure, but it's still remain open how to tackle response times.


## Inference criteria
<!-- What criteria will you use to make inferences? Please describe the information youÍll use (e.g. p-values, bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this?

p-values, confidence intervals, and effect sizes are standard means for making an inference, and any level is acceptable, though some criteria must be specified in this or previous fields. Bayesian analyses should specify a Bayes factor or a credible interval. If you are selecting models, then how will you determine the relative quality of each? In regards to multiple comparisons, this is a question with few "wrong" answers. In other words, transparency is more important than any specific method of controlling the false discovery rate or false error rate. One may state an intention to report all tests conducted or one may conduct a specific correction procedure; either strategy is acceptable.

Example: We will use the standard p<.05 criteria for determining if the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct. The post-hoc Tukey-Kramer test adjusts for multiple comparisons. -->


We will use the standard p<.05 criteria for determining if the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct. We expect to see significant interaction between group and pair type, where inference will have significantly higher performance in delay condition than in non-delay condition, where we expect performance on the chance level. Further we will provide a standard error as a measure of how well our sample represents the population. Effect sizes for performance between groups will be provided in proportions. Effect sizes for response times will be reported with confidence intervals.



## Data exclusion
<!-- How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? Will you use any awareness check? Any rule for excluding a particular set of data is acceptable. One may describe rules for excluding a participant or for identifying outlier data.

Example: No checks will be performed to determine eligibility for inclusion besides verification that each subject answered each of the three tastiness indices. Outliers will be included in the analysis. -->

We will assess the outliers by measuring a cook distance and will expore an individual cases. If the outliers will represent general population deviation and won't be considered as errors, e.g. missing responses, they will be included in the analysis.


## Missing data
<!-- How will you deal with incomplete or missing data? Any relevant explanation is acceptable. As a final reminder, remember that the final analysis must follow the specified plan, and deviations must be either strongly justified or included as a separate, exploratory analysis.

Example: If a subject does not complete any of the three indices of tastiness, that subject will not be included in the analysis. -->

If the subjects don't complete training or testing, they will be excluded from analysis. If participants fail to pass the training until reaching 75% criterion within 30 blocks, they will be also excluded.


## Exploratory analyses (optional)
<!-- If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time.

Example: We expect that certain demographic traits may be related to taste preferences. Therefore, we will look for relationships between demographic variables (age, gender, income, and marital status) and the primary outcome measures of taste preferences. -->

Enter your response here.


# Other

## Other (Optional)
<!-- If there is any additional information that you feel needs to be included in your preregistration, please enter it here. Literature cited, disclosures of any related work such as replications or work that uses the same data, or other context that will be helpful for future readers would be appropriate here. -->

Enter your response here.


# References
## 
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
\noindent
